runtime: nodejs20
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|css|png|jpg|jpeg|svg|webp))
    static_files: build/\1
    upload: build/.*

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
